### ISSUE TITLE
Request to modify description

### ISSUE THREAD

**Issue by bottiger1** [TF2CutContentWiki/TF2ServersidePlayerAttachmentFixer#1]
Hello I just stumbled across this github page and noticed the description seems to unfairly single out skial, a community I am affiliated with.

I just wanted to set the record straight that many other servers used this for many years before we even knew about it, especially the community called Wonderland and their sub-communities like Otaku. They rose from complete obscurity to over 1000 concurrent players while we lost over half of ours.

We contacted multiple people at Valve about this multiple times over the time span of a year and did not hear a single thing. It should also be noted that the only place modifying cosmetics is against the terms of service is in the quickplay FAQ, and as you know, quickplay was entirely removed in 2016.

**Comment by TF2CutContentWiki** [comment]
Wah.
