### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by 1umbrykid** [TF2CutContentWiki/TF2ServersidePlayerAttachmentFixer#2]
hi im dumb and i have no ideia how sourcemod works! 

idk how to enable it

(btw im trying to get it working with the "weaponmodel overrite"

**Comment by gdfsgdfg** [comment]
I was also hoping it would fix the golden pan being normal but it doesn't. Please fix that as well if possible.

**Comment by TF2CutContentWiki** [comment]
> hi im dumb and i have no ideia how sourcemod works!
> 
> idk how to enable it
> 
> (btw im trying to get it working with the "weaponmodel overrite"
Strange that it isn't working with that custom attribute but I've also received reports from others who have had issues with that particular custom attrib plugin. I may have to take a look at that plugin and see if it's working correctly.

> I was also hoping it would fix the golden pan being normal but it doesn't. Please fix that as well if possible.
That is an entirely different issue that this plugin isn't meant to resolve. There are ways to resolve it, but it's been a while since I've done anything SourceMod related. I'll have to set up a server and get a SourceMod install going and see what's what.

**Comment by 1umbrykid** [comment]
i did, no changes, still invisible models

the git and allied mods page mention this:

"HOWEVER, the model won't show on non-bot clients. There is a missing property to enable it, but it's your job to find it ( in case you find it and want to put it in the plugin, I wrote a comment where you should put it ). It's not allowed to share it publicly."

**Comment by TF2CutContentWiki** [comment]
> i did, no changes, still invisible models
> 
> the git and allied mods page mention this:
> 
> "HOWEVER, the model won't show on non-bot clients. There is a missing property to enable it, but it's your job to find it ( in case you find it and want to put it in the plugin, I wrote a comment where you should put it ). It's not allowed to share it publicly."

Yeah that's the m_bValidatedAttachedEntity netprop that this plugin sets. But people still reported issues with the attribute model change not being visible despite using this plugin.

This plugin only fires on the OnEntityCreated event. I'm starting to wonder if the attribute plugin does the model change in a way that doesn't result in OnEntityCreated being fired....

**Comment by gdfsgdfg** [comment]
> I was also hoping it would fix the golden pan being normal but it doesn't. Please fix that as well if possible.

https://github.com/punteroo/TF2-Item-Plugins This has a weapon plugin that gives a proper gpan, so its fine now.
